version: 2.1
orbs:
  docker: circleci/docker@1.0.1
jobs:
  build-and-push:
    executor: docker/docker
    steps:
      - setup_remote_docker
      - checkout
      - docker/check
      - docker/build:
          image: overdrive1g/hunspell-ru
      - docker/push:
          digest-path: /tmp/digest.txt
          image: overdrive1g/hunspell-ru
      - run:
          command: |
            echo "Digest is: $(</tmp/digest.txt)"


workflows:
  commit:
    jobs:
      - build-and-push